export const genreSet = [
    { label: 'Rock', value: 'Rock' },
    { label: 'Electronic', value: 'Electronic' },
    { label: 'Pop', value: 'Pop' },
    { label: 'Folk, World, & Country', value: 'Folk, World, & Country' },
    { label: 'Jazz', value: 'Jazz' },
    { label: 'Rock', value: 'Rock' },
    { label: 'Funk/Soul', value: 'Funk/Soul' },
    { label: 'Classical', value: 'Classical' },
    { label: 'Hip Hop', value: 'Hip Hop' },
    { label: 'Latin', value: 'Latin' },
    { label: 'Stage & Screen', value: 'Stage & Screen' },
    { label: 'Reggae', value: 'Reggae' },
    { label: 'Non-Music', value: 'Non-Music' },
    { label: 'Children\'s', value: 'Children\'s' },
    { label: 'Brass & Military', value: 'Brass & Military' },
];

export const styleSet = [
    { label: "Pop Rock", value: "Pop Rock" },
    { label: "House", value: "House" },
    { label: "Hip Hop", value: "Hip Hop" },
    { label: "Techno", value: "Techno" },
    { label: "Disco", value: "Disco" },
    { label: "Ambient", value: "Ambient" },
    { label: "Experimental", value: "Experimental" },
    { label: "Alternative Rock", value: "Alternative Rock" },
    { label: "Synth-pop", value: "Synth-pop" },
    { label: "Indie Rock", value: "Indie Rock" },
    { label: "Minimal", value: "Minimal" },
    { label: "Drum n Bass", value: "Drum n Bass" },
    { label: "Soul", value: "Soul" },
    { label: "Punk", value: "Punk" },
    { label: "Indie Pop", value: "Indie Pop" },
    { label: "Downtempo", value: "Downtempo" },
    { label: "RnB/Swing", value: "RnB/Swing" },
    { label: "Industrial", value: "Industrial" },
    { label: "Noise", value: "Noise" },
    { label: "Folk Rock", value: "Folk Rock" },
    { label: "Deep House", value: "Deep House" },
    { label: "Hardcore", value: "Hardcore" },
    { label: "Acid", value: "Acid" },
    { label: "Garage Rock", value: "Garage Rock" },
    { label: "Ballad", value: "Ballad" },
    { label: "Reggae", value: "Reggae" },
    { label: "Dub", value: "Dub" },
    { label: "Psychedelic Rock", value: "Psychedelic Rock" },
    { label: "Heavy Metal", value: "Heavy Metal" },
    { label: "Prog Rock", value: "Prog Rock" },
    { label: "Folk", value: "Folk" },
    { label: "Breaks", value: "Breaks" },
    { label: "Tech House", value: "Tech House" },
    { label: "Trap", value: "Trap" },
    { label: "J-pop", value: "J-pop" },
    { label: "Chanson", value: "Chanson" },
    { label: "Hard Rock", value: "Hard Rock" },
    { label: "Art Rock", value: "Art Rock" },
    { label: "Pop Rap", value: "Pop Rap" },
    { label: "Gospel", value: "Gospel" },
    { label: "Latin", value: "Latin" },
    { label: "Country Rock", value: "Country Rock" },
    { label: "Eurodance", value: "Eurodance" },
    { label: "Schlager", value: "Schlager" },
    { label: "Jazz-Funk", value: "Jazz-Funk" },
    { label: "K-pop", value: "K-pop" },
    { label: "Contemporary R&B", value: "Contemporary R&B" },
    { label: "Blues", value: "Blues" },
    { label: "Speed Metal", value: "Speed Metal" },
    { label: "Hardcore Hip-Hop", value: "Hardcore Hip-Hop" },
    { label: "Drone", value: "Drone" },
    { label: "Leftfield", value: "Leftfield" },
    { label: "Pop Punk", value: "Pop Punk" },
    { label: "Classic Rock", value: "Classic Rock" },
    { label: "Garage House", value: "Garage House" },
    { label: "Death Metal", value: "Death Metal" },
    { label: "Soul-Jazz", value: "Soul-Jazz" },
    { label: "Comedy", value: "Comedy" },
    { label: "Melodic Metalcore", value: "Melodic Metalcore" },
    { label: "Punk Rock", value: "Punk Rock" },
    { label: "New Wave", value: "New Wave" },
    { label: "Grindcore", value: "Grindcore" },
    { label: "Post Rock", value: "Post Rock" },
    { label: "Avantgarde", value: "Avantgarde" },
    { label: "Dubstep", value: "Dubstep" },
    { label: "Darkwave", value: "Darkwave" },
    { label: "Acid House", value: "Acid House" },
    { label: "Thrash Metal", value: "Thrash Metal" },
    { label: "Hi NRG", value: "Hi NRG" },
    { label: "Ballroom", value: "Ballroom" },
    { label: "Power Pop", value: "Power Pop" },
    { label: "Indie", value: "Indie" },
    { label: "Swing", value: "Swing" },
    { label: "Score", value: "Score" },
    { label: "Polka", value: "Polka" },
    { label: "Boom Bap", value: "Boom Bap" },
    { label: "Metalcore", value: "Metalcore" },
    { label: "Trance", value: "Trance" },
    { label: "Dancehall", value: "Dancehall" },
    { label: "Baroque", value: "Baroque" },
    { label: "Drill", value: "Drill" },
    { label: "Disco Polo", value: "Disco Polo" },
    { label: "Free Jazz", value: "Free Jazz" },
    { label: "Lounge", value: "Lounge" },
    { label: "Rhythm & Blues", value: "Rhythm & Blues" },
    { label: "Musical", value: "Musical" },
    { label: "Opera", value: "Opera" },
    { label: "Breakbeat", value: "Breakbeat" },
    { label: "Chiptune", value: "Chiptune" },
    { label: "Electro", value: "Electro" },
    { label: "Spoken Word", value: "Spoken Word" },
    { label: "Glitch", value: "Glitch" },
    { label: "Indian Classical", value: "Indian Classical" },
    { label: "Post-Punk", value: "Post-Punk" },
    { label: "Ska", value: "Ska" },
    { label: "Bossa Nova", value: "Bossa Nova" },
    { label: "Glam", value: "Glam" },
    { label: "Black Metal", value: "Black Metal" },
    { label: "Jumpstyle", value: "Jumpstyle" },
    { label: "Funk", value: "Funk" },
    { label: "Hip-Hop", value: "Hip-Hop" },
    { label: "Grime", value: "Grime" },
    { label: "Vaporwave", value: "Vaporwave" },
    { label: "Jungle", value: "Jungle" },
    { label: "Be-bop", value: "Be-bop" },
    { label: "Noise Pop", value: "Noise Pop" },
    { label: "Euro House", value: "Euro House" },
    { label: "Tech Trance", value: "Tech Trance" },
    { label: "IDM", value: "IDM" },
    { label: "Dream Pop", value: "Dream Pop" },
    { label: "Neo Soul", value: "Neo Soul" },
    { label: "Jangle Pop", value: "Jangle Pop" },
    { label: "Afrobeat", value: "Afrobeat" },
    { label: "Crust", value: "Crust" },
    { label: "Viking Metal", value: "Viking Metal" },
    { label: "Breakcore", value: "Breakcore" },
    { label: "Lo-Fi", value: "Lo-Fi" },
    { label: "Progressive House", value: "Progressive House" },
    { label: "Hardstyle", value: "Hardstyle" },
    { label: "Big Band", value: "Big Band" },
    { label: "Latin Jazz", value: "Latin Jazz" },
    { label: "Chillwave", value: "Chillwave" },
    { label: "Jazz Rap", value: "Jazz Rap" },
    { label: "Footwork", value: "Footwork" },
    { label: "Bass Music", value: "Bass Music" },
    { label: "Italo-Disco", value: "Italo-Disco" },
    { label: "Future Bass", value: "Future Bass" },
    { label: "Post-Hardcore", value: "Post-Hardcore" },
    { label: "Neo-Classical", value: "Neo-Classical" },
    { label: "Beatdown", value: "Beatdown" },
    { label: "Cumbia", value: "Cumbia" },
    { label: "Dance-pop", value: "Dance-pop" },
    { label: "Soca", value: "Soca" },
    { label: "Country", value: "Country" },
    { label: "Goth Rock", value: "Goth Rock" },
    { label: "Shoegaze", value: "Shoegaze" },
    { label: "Psytrance", value: "Psytrance" },
    { label: "Jazz Rock", value: "Jazz Rock" },
    { label: "Indie Folk", value: "Indie Folk" },
    { label: "City Pop", value: "City Pop" },
    { label: "Math Rock", value: "Math Rock" },
    { label: "MPB", value: "MPB" },
    { label: "Samba", value: "Samba" },
    { label: "Bossanova", value: "Bossanova" },
    { label: "Honky Tonk", value: "Honky Tonk" },
    { label: "Bluegrass", value: "Bluegrass" },
    { label: "Nu Metal", value: "Nu Metal" },
    { label: "Electro House", value: "Electro House" },
    { label: "Roots Reggae", value: "Roots Reggae" },
    { label: "Sludge Metal", value: "Sludge Metal" },
    { label: "Barbershop", value: "Barbershop" },
    { label: "Tango", value: "Tango" },
    { label: "Reggaeton", value: "Reggaeton" },
    { label: "Hard Trance", value: "Hard Trance" },
    { label: "Nu-Disco", value: "Nu-Disco" },
    { label: "Synthwave", value: "Synthwave" },
    { label: "Hard Techno", value: "Hard Techno" },
    { label: "Kawaii Future Bass", value: "Kawaii Future Bass" },
    { label: "EDM", value: "EDM" },
    { label: "Folk Metal", value: "Folk Metal" },
    { label: "Hardbass", value: "Hardbass" },
    { label: "Rai", value: "Rai" },
    { label: "Electroclash", value: "Electroclash" },
    { label: "Drumfunk", value: "Drumfunk" },
    { label: "Electroacoustic", value: "Electroacoustic" },
    { label: "Britpop", value: "Britpop" },
    { label: "Juke", value: "Juke" },
    { label: "Neo-Psychedelia", value: "Neo-Psychedelia" },
    { label: "Deep Techno", value: "Deep Techno" },
    { label: "Orchestral", value: "Orchestral" },
    { label: "Euro-Trance", value: "Euro-Trance" },
    { label: "Melodic House", value: "Melodic House" },
    { label: "Slowcore", value: "Slowcore" },
    { label: "Gypsy Jazz", value: "Gypsy Jazz" },
    { label: "Mambo", value: "Mambo" },
    { label: "UK Garage", value: "UK Garage" },
    { label: "Speedcore", value: "Speedcore" },
    { label: "Future Funk", value: "Future Funk" },
    { label: "Afrobeats", value: "Afrobeats" },
    { label: "Yacht Rock", value: "Yacht Rock" },
    { label: "Minimal Techno", value: "Minimal Techno" },
    { label: "Country Pop", value: "Country Pop" }
];
